// AUTO-GENERATED by tools/bake-theaters.mjs — do not edit by hand.
// Real-world elevation patches baked from public-domain DEMs (AWS Open Data
// terrain tiles). Each entry pairs with public/theaters/<id>.bin:
// size×size Uint16 LE row-major (north up), heights quantized min→max.
export interface TheaterMeta {
  id: string
  name: string
  sub: string
  lat: number
  lon: number
  size: number        // pixels per side
  metersPerPx: number // ground distance per pixel (== one map cell)
  minElev: number     // meters at quantized 0
  maxElev: number     // meters at quantized 65535
}

export const THEATER_INDEX: readonly TheaterMeta[] = [
  { id: 'fulda', name: 'FULDA GAP', sub: "Central German ridge-and-farmland · the NATO tripwire corridors", lat: 50.51, lon: 9.75, size: 512, metersPerPx: 50, minElev: 226.1, maxElev: 919.9 },
  { id: 'ntc', name: 'NTC — MOJAVE', sub: "High-desert washes and ridgelines · the Army's own battlefield", lat: 35.35, lon: -116.65, size: 512, metersPerPx: 50, minElev: 470.3, maxElev: 1611.4 },
  { id: 'tigris', name: 'TIGRIS VALLEY', sub: "River plain, bluffs and wadis on the road to Mosul", lat: 35.82, lon: 43.3, size: 512, metersPerPx: 50, minElev: 155.9, maxElev: 279.6 },
  { id: 'donbas', name: 'DONBAS STEPPE', sub: "Open steppe and shallow ridges · long sightlines, little cover", lat: 47.8, lon: 37.25, size: 512, metersPerPx: 50, minElev: 107.7, maxElev: 235.8 },
  { id: 'ardennes', name: 'ARDENNES', sub: "Forested ridge and valley country · the Bulge", lat: 50, lon: 5.72, size: 512, metersPerPx: 50, minElev: 291.9, maxElev: 563.4 },
  { id: 'arghandab', name: 'ARGHANDAB VALLEY', sub: "Green-zone river valley walled by desert ridges", lat: 31.7, lon: 65.55, size: 512, metersPerPx: 50, minElev: 945.6, maxElev: 1640.7 },
  { id: 'golan', name: 'GOLAN HEIGHTS', sub: "Volcanic tank country · the plateau of the Valley of Tears", lat: 33.05, lon: 35.78, size: 512, metersPerPx: 50, minElev: -45.6, maxElev: 1192.6 },
]
